"""Integration tests for PDF processing with real PDF files.

These tests use actual PDF files generated by scripts/generate_test_pdfs.py
to verify end-to-end PDF processing functionality.

Note: Scanned/image-only PDFs are still tested via mocks in unit tests
since true scanned PDFs cannot be generated programmatically.
"""

from pathlib import Path

import pytest

from medical_bill_analyzer.pdf.extractor import extract_text_from_pdf
from medical_bill_analyzer.pdf.utils import get_pdf_hash, get_pdf_info
from medical_bill_analyzer.pdf.validator import is_scanned_pdf, validate_pdf

# Path to test PDF files
TEST_DATA_DIR = Path(__file__).parent.parent / "test_data" / "sample_bills"
VALID_BILL_PDF = TEST_DATA_DIR / "valid_bill.pdf"
MULTIPAGE_BILL_PDF = TEST_DATA_DIR / "multipage_bill.pdf"
MINIMAL_TEXT_PDF = TEST_DATA_DIR / "minimal_text.pdf"
EMPTY_TEXT_PDF = TEST_DATA_DIR / "empty_text.pdf"


class TestRealPDFExtraction:
    """Test text extraction with real PDF files."""

    def test_extract_from_valid_bill(self):
        """Test extracting text from a valid German medical bill PDF."""
        assert VALID_BILL_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        text = extract_text_from_pdf(VALID_BILL_PDF)

        # Verify German medical bill content is extracted
        assert "Dr. med. Anna Müller" in text
        assert "Rechnung" in text
        assert "Max Mustermann" in text
        assert "GOÄ" in text
        assert "EUR" in text
        assert "Gesamtbetrag" in text

    def test_extract_from_multipage_bill(self):
        """Test extracting text from multi-page PDF."""
        assert MULTIPAGE_BILL_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        text = extract_text_from_pdf(MULTIPAGE_BILL_PDF)

        # Verify content from both pages
        assert "Dr. Thomas Schmidt" in text
        assert "Zahnarztpraxis" in text
        assert "Maria Beispiel" in text
        assert "Seite 1 von 2" in text
        assert "Seite 2 von 2" in text
        assert "Gesamtbetrag" in text

        # Verify pages are concatenated (should have multiple page markers)
        assert text.count("GOÄ") > 10  # Should have many line items across pages

    def test_extract_from_minimal_text_pdf(self):
        """Test extracting from PDF with minimal text."""
        assert MINIMAL_TEXT_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        text = extract_text_from_pdf(MINIMAL_TEXT_PDF)

        # Should extract the minimal text present
        assert "Dr. Minimal Text" in text
        assert len(text) < 50  # Very short

    def test_extract_from_empty_text_pdf(self):
        """Test extracting from PDF with no text."""
        assert EMPTY_TEXT_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        text = extract_text_from_pdf(EMPTY_TEXT_PDF)

        # Should return empty string for PDF with no text
        assert text == ""


class TestRealPDFValidation:
    """Test PDF validation with real PDF files."""

    def test_validate_valid_bill(self):
        """Test validation of valid German medical bill PDF."""
        assert VALID_BILL_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        result = validate_pdf(VALID_BILL_PDF)

        assert result.is_valid
        assert result.has_text
        assert not result.is_scanned
        assert result.page_count == 1
        assert result.file_size_bytes > 0
        assert result.is_processable
        assert len(result.errors) == 0

    def test_validate_multipage_bill(self):
        """Test validation of multi-page PDF."""
        assert MULTIPAGE_BILL_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        result = validate_pdf(MULTIPAGE_BILL_PDF)

        assert result.is_valid
        assert result.has_text
        assert not result.is_scanned
        assert result.page_count == 2
        assert result.is_processable

    def test_validate_minimal_text_pdf(self):
        """Test validation detects minimal text as scanned."""
        assert MINIMAL_TEXT_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        result = validate_pdf(MINIMAL_TEXT_PDF)

        # Valid structure but detected as scanned due to minimal text
        assert result.is_valid
        assert not result.has_text  # Below MIN_TEXT_LENGTH threshold
        assert result.is_scanned
        assert not result.is_processable
        assert len(result.warnings) > 0
        assert any("scanned" in w.lower() for w in result.warnings)

    def test_validate_empty_text_pdf(self):
        """Test validation of PDF with no text."""
        assert EMPTY_TEXT_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        result = validate_pdf(EMPTY_TEXT_PDF)

        # Valid structure but no text
        assert result.is_valid
        assert not result.has_text
        assert result.is_scanned
        assert not result.is_processable

    def test_is_scanned_valid_bill(self):
        """Test is_scanned_pdf returns False for text-based PDF."""
        assert VALID_BILL_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        is_scanned = is_scanned_pdf(VALID_BILL_PDF)

        assert is_scanned is False

    def test_is_scanned_minimal_text(self):
        """Test is_scanned_pdf returns True for minimal text PDF."""
        assert MINIMAL_TEXT_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        is_scanned = is_scanned_pdf(MINIMAL_TEXT_PDF)

        assert is_scanned is True


class TestRealPDFUtils:
    """Test PDF utility functions with real PDF files."""

    def test_hash_consistency(self):
        """Test hash calculation is consistent for same file."""
        assert VALID_BILL_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        hash1 = get_pdf_hash(VALID_BILL_PDF)
        hash2 = get_pdf_hash(VALID_BILL_PDF)

        assert hash1 == hash2
        assert len(hash1) == 64  # SHA256 hex length

    def test_hash_uniqueness(self):
        """Test different PDFs have different hashes."""
        assert VALID_BILL_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"
        assert MULTIPAGE_BILL_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        hash1 = get_pdf_hash(VALID_BILL_PDF)
        hash2 = get_pdf_hash(MULTIPAGE_BILL_PDF)

        assert hash1 != hash2

    def test_get_info_valid_bill(self):
        """Test getting info from valid PDF."""
        assert VALID_BILL_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        info = get_pdf_info(VALID_BILL_PDF)

        assert info["filename"] == "valid_bill.pdf"
        assert info["size_bytes"] > 0
        assert info["size_mb"] > 0
        assert isinstance(info["hash"], str)
        assert len(info["hash"]) == 64

    def test_get_info_multipage_bill(self):
        """Test getting info from multi-page PDF."""
        assert MULTIPAGE_BILL_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        info = get_pdf_info(MULTIPAGE_BILL_PDF)

        assert info["filename"] == "multipage_bill.pdf"
        # Multi-page should be larger
        valid_info = get_pdf_info(VALID_BILL_PDF)
        assert info["size_bytes"] > valid_info["size_bytes"]


class TestEndToEndWorkflow:
    """Test complete end-to-end PDF processing workflows."""

    def test_complete_workflow_valid_bill(self):
        """Test complete workflow: validate -> extract -> hash."""
        assert VALID_BILL_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        # Step 1: Validate
        validation = validate_pdf(VALID_BILL_PDF)
        assert validation.is_processable

        # Step 2: Extract text
        text = extract_text_from_pdf(VALID_BILL_PDF)
        assert len(text) > 100
        assert "Rechnung" in text

        # Step 3: Calculate hash for duplicate detection
        file_hash = get_pdf_hash(VALID_BILL_PDF)
        assert len(file_hash) == 64

        # Step 4: Get metadata
        info = get_pdf_info(VALID_BILL_PDF)
        assert info["hash"] == file_hash

    def test_complete_workflow_scanned_detection(self):
        """Test workflow correctly identifies and rejects scanned PDF."""
        assert MINIMAL_TEXT_PDF.exists(), "Test PDF not found. Run scripts/generate_test_pdfs.py"

        # Step 1: Validate
        validation = validate_pdf(MINIMAL_TEXT_PDF)
        assert not validation.is_processable  # Should reject
        assert validation.is_scanned

        # Step 2: Can still extract (minimal) text
        text = extract_text_from_pdf(MINIMAL_TEXT_PDF)
        assert len(text) < 50

        # Step 3: Hash still works
        file_hash = get_pdf_hash(MINIMAL_TEXT_PDF)
        assert len(file_hash) == 64


@pytest.mark.skipif(
    not VALID_BILL_PDF.exists(),
    reason="Test PDFs not found. Run: python scripts/generate_test_pdfs.py",
)
class TestGermanContentExtraction:
    """Test extraction of German-specific content."""

    def test_extracts_german_umlauts(self):
        """Test that German umlauts (ä, ö, ü) are extracted correctly."""
        text = extract_text_from_pdf(VALID_BILL_PDF)

        # Check for German umlauts from the test PDF
        assert "Müller" in text  # ü
        assert "Fachärztin" in text  # ä

    def test_extracts_german_medical_terms(self):
        """Test extraction of German medical/billing terminology."""
        text = extract_text_from_pdf(VALID_BILL_PDF)

        # German medical billing terms
        assert "Rechnung" in text  # Invoice
        assert "Patient" in text
        assert "Gesamtbetrag" in text  # Total amount
        assert "EUR" in text

    def test_extracts_goa_codes(self):
        """Test extraction of GOÄ (German medical fee schedule) codes."""
        text = extract_text_from_pdf(VALID_BILL_PDF)

        # GOÄ codes from our test PDF
        assert "GOÄ" in text
        # Specific services mentioned in valid_bill.pdf
        assert "Beratung" in text or "Untersuchung" in text
